### ISSUE TITLE
paperclip-dropbox evaluating nil.[] error

### ISSUE THREAD

**Issue by joelmaranhao** [janko-m/paperclip-dropbox#11]
Just trying out paperclip-dropbox but without much success. Here what I have done.

In my Gemfile:

``` ruby
gem 'paperclip'
gem "paperclip-dropbox"
```

Created an App on dropbox and followed these instructions: https://github.com/janko-m/paperclip-dropbox

In my dropbox.yml

``` yml
development:
  app_key: APP_KEY
  app_secret: APP_SECRET
  access_token: ACCESS_TOKEN
  access_token_secret: ACCESS_TOKEN_SECRET
  user_id: USER_ID

production:
  app_key: APP_KEY
  app_secret: APP_SECRET
  access_token: ACCESS_TOKEN
  access_token_secret: ACCESS_TOKEN_SECRET
  user_id: USER_ID
```

In my User model:

``` ruby
has_attached_file :avatar, 
  :styles => {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>' }
```

In my view:

``` erb
<%= image_tag @user_profile.avatar.url(:square), :size => '100x100' %>
```

Error message:

```
You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.[]  
Pointing at my image_tag line of code.
```

Note that paperclip worked real well using the local filesystem.

Any ideas?
